name = "hugo-geo"
license = "MIT"
source_repo = "https://github.com/alexurquhart/hugo-geo"
description = "Personal blog theme for Hugo"
tags = ["blog", "company"]

[author]
    name = "Alex Urquhart"
    email = "alexurquhart@gmail.com"
    url = "https://alexurquhart.com"
