baseurl = "http://replace-this-with-your-hugo-site.com/"
relativeURLs = false
languageCode = "en-us"
title = "Your Name"
disqusShortname = "shortcode-here"
paginate = 5
googleAnalytics = "code-here"
copyright = "2001 - 2017"
theme = "hugo-geo"

[author]
    name = "My Name Here"

[taxonomies]
    tag = "tags"
    tutorial = "tutorials"

[params]
    profilepic = "img/profile.png"
    subtitle = "My Hugo Blog"
    tagline = "What I'm Thinking"
    attribution = true
    twitterwidgeturl = "https://twitter.com/alexanderurq"
    sharebuttons = [
        "email",
        "print",
        "rss",
        "facebook",
        "twitter",
        "linkedin",
        "reddit",
        "googleplus"
    ]

[[menu.sidenav]]
    name = "Blog"
    identifier = "blog"
    url = "/"
    weight = -1
[[menu.sidenav]]
    name = "Tutorials"
    identifier = "tutorials"
    url = "/tutorial/"
    weight = 1

[[menu.sidebar]]
    pre = '<img src="/img/do.png" class="responsive pure-img>'
    url = "https://m.do.co/c/78ae6b852549"

[[menu.social]]    
    name = "GitHub"
    url = "https://www.github.com/alexanderurq"
    pre = '<i class="fa fa-github" aria-hidden="true"></i>'
    weight = 0

[[menu.social]]
    name = "Twitter"
    url = "https://twitter.com/alexanderurq"
    pre = '<i class="fa fa-twitter" aria-hidden="true"></i>'
    weight = 1

[[menu.social]]    
    name = "E-Mail"
    url = "mailto:alexurquhart@gmail.com"
    pre = '<i class="fa fa-envelope-o" aria-hidden="true"></i>'
    weight = 2

[[menu.social]]    
    name = "LinkedIn"
    url = "https://www.linkedin.com/in/alex-urquhart-65979695"
    pre = '<i class="fa fa-linkedin" aria-hidden="true"></i>'
    weight = 3

[[menu.footer]]
    name = "Link 1"
    url = "#"
[[menu.footer]]
    name = "Link 2"
    url = "#"